= Ten Chee Onn David Jonathan - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CRM Book

---

== Overview

CRM Book application aims to assist Salespeople by implementing the most important functionality of a CRM System, that is, managing their business contacts and clients. In a CRM, buisness contacts are seperated into two categories, Leads and Contacts. Companies are usually added as Contacts.

Some unique features of this CRM that benefits the individual Salesperson even more is an enhanced detection of duplicates through fields such as email and phone number, importing of a CSV file of leads that the salesperson may have bought through a mailing list or obtained through a tradeshow, sharing of posts about their company through LinkedIn, as well as seeing directions to their Lead’s office through Google Maps. It is important to note that these features all enhance the experience of the salesperson, and does not distract from the core functionality of managing their relationship with their leads and contacts.

The user interacts with CRM Book using a CLI, and it has a GUI created with JavaFX. It is written in Java.

== Summary of contributions

* *Major enhancement*: Post a Status Update onto LinkedIn
** What it does: After a Salesperson has logged in to LinkedIn via the linkedin_login command, he will be able to post status updates via the linkedin_share command.
** Justification: This feature improves CRM Book significantly in that it does not require the Salesperson to navigate away from CRM Book just to post a status update about their company. In the Sales and Marketing world, LinkedIn is used often to promote news articles and other related company marketing materials, and this feature reduces the friction generated by doing
** Highlights: This enhancement required an in-depth research into encryption and storing of API Secrets in a native application. It also made use of LinkedIn's OAuth2 authentication scheme as well as API be able to work. The implementation was challenging as it required the exploration of new APIs outside of the address book. The enhancement also required studying more about events and how they are handled, as well as handling different threads on Java FX, in particular handling the 'Not on FX application thread' exception.
** Credits: LinkedIn API

* *Major enhancement*: View directions to a customer or potential customer's office via Google Maps
** What it does: After a Salesperson has set their office location on the CRM Book, they will be able to view directions to a customer's or potential customer's office by clicking on their name.
** Justification: This feature improves CRM Book significantly in that it does not require the Salesperson to navigate away from CRM Book just to find directions to their client's location, or to know how long it will take to get there. Salespeople in general travel to other offices often to do a demo or to pitch a product. With this feature, the salesperson will not have to use their smartphone to view directions while still in the office. Rather, they will be able to view directions in the CRM Book and then leave the office when necessary.
** Highlights: This enhancement involved learning more about Google Map's webservice, studying between the different APIs and other options that they provided, as well as research on how to use the config.json file in the CRM Book.
** Credits: Google Maps URLs

* *Code contributed*: [https://github.com/CS2103JAN2018-F11-B1/main/blob/master/collated/functional/DavidTen.md[Functional code]] [https://github.com/CS2103JAN2018-F11-B1/main/blob/master/collated/test/DavidTen.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` - `v1.5rc` (5 releases) on GitHub
** Community:
*** Reported bugs and suggestions for other teams in the class (examples: https://github.com/CS2103JAN2018-W13-B3/main/issues/157[Issue #157], https://github.com/CS2103JAN2018-W13-B3/main/issues/132[Issue #132], https://github.com/CS2103JAN2018-W13-B3/main/issues/133[Issue #133], https://github.com/CS2103JAN2018-W13-B3/main/issues/134[Issue #134], https://github.com/CS2103JAN2018-W13-B3/main/issues/136[Issue #136], https://github.com/CS2103JAN2018-W13-B3/main/issues/139[Issue #139], https://github.com/CS2103JAN2018-W13-B3/main/issues/140[Issue #140], https://github.com/CS2103JAN2018-W13-B3/main/issues/141[Issue #141], https://github.com/CS2103JAN2018-W13-B3/main/issues/145[Issue #145], https://github.com/CS2103JAN2018-W13-B3/main/issues/149[Issue #149])
*** Contributed to forum discussions (examples:  https://nus-cs2103-ay1718s2.slack.com/archives/C8K2W5WTH/p1523377709000303[1], https://nus-cs2103-ay1718s2.slack.com/archives/C8K2W5WTH/p1521906587000027[2], https://nus-cs2103-ay1718s2.slack.com/archives/C8K2W5WTH/p1521473983000781[3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

<<../UserGuide.adoc#22-log-in-to-linkedin--linklog-linkedin_login\--linkedin-login,LinkedIn Login>>

<<../UserGuide.adoc#23-share-a-post-on-linkedin--linkshare-linkedin_share\--linkedin-share,LinkedIn Share>>

<<../UserGuide.adoc#1-introduction\--introduction,Introduction>>

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

<<../DeveloperGuide.adoc#35-leads-and-contacts-feature,Leads and Contacts>>
