= ZHU Leyan - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: CRM Book

---

== Overview

CRM Book is a desktop address book application used for ???. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to import a CSV file*
** What it does: allows the user to import a CSV file at a time.
** Justification: This feature improves the product significantly because a user can add a large number of persons into the CRM Book at the same time without typing so many `add` command
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a remark command that allows the user to add/remove/edit the remark of a person.

* *Minor enhancement*: added a sort command that allows the user to sort all persons in the list by name alphabetically.

* *Code contributed*: [???[Functional code]] [???[Test code]]


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=remark]

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=bulkimport]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=remark]

include::../DeveloperGuide.adoc[tag=bulkimport]
